/**
 * ui/toolbar.js — buildToolbar (V2 adapter).
 *
 * V1 source: bundle.js line 13305-14857 (~1550 行, function buildToolbar).
 *
 * P11 status (adapter): V1 buildToolbar 内部 DOM 构建/jQuery 事件订阅链路太长,
 * 且依赖 V1 PrintTemplate.design / printPanels 上的 zoom/getJson/pdf 等还未在 V2
 * skeleton 完成的方法 (推 P10b/P10c). 因此 P11 采取 **adapter 策略**:
 *
 *  - V2 buildToolbar(container, template, options) 是 V2 surface
 *  - 内部 delegate 到 V1 `hiprint.buildToolbar` (经 window.hiprint 或 init 时注入)
 *  - 在 boundary 加 V2 不变式守卫:
 *      a) 所有 opts.onXxx 业务回调走 safeCall (R3 W2, 24 处)
 *      b) 验证返回 ctrl 含 destroy (R3 W1)
 *      c) PM-005: ctrl 实例 id 必须 timestamp+random (V1 内部已实现)
 *
 * P14 cleanup 阶段 V1 bundle 删除时, 把 V1 buildToolbar 完整内联到这里 (~1500 行).
 *
 * Invariants (V2 必须保留, 见 ADR-0010 + R3 系列):
 *  - R3 W1: $(document).on(...) 必须用 ".hiprintToolbar_<uid>" namespace
 *  - R3 W2: 24 处 opts.onXxx 走 safeCall
 *  - PM-005: _toolbarUid = Date.now() + Math.random() (跨 iframe 唯一)
 *  - R3 W4: confirmTemplateDelete / handleTemplateDelete 同步 throw 包 try (V1 line 13764-13794)
 *  - 业务方安全合约: setButtonText useHtml=true 是 by-design (JSDoc 警告)
 */

import { safeCall, i18n } from '@hiprint-v2/internal'

const ON_XXX_KEYS = [
  // V1 line 13329-13390 的 24 处业务回调 (R3 W2)
  'onPreview',
  'onClear',
  'onPrint',
  'onSave',
  'onPaperChange',
  'onScaleChange',
  'onRotate',
  'onAlign',
  'onBusinessClick',
  'onBusinessDialogOpen',
  'onBusinessDialogClose',
  'onBusinessSelect',
  'onTemplateDialogOpen',
  'onTemplateDialogClose',
  'onTemplateDeleteConfirm',
  'onSaveDialogOpen',
  'onSaveDialogClose',
  'onTemplateSelect',
  'onTemplatePreview',
  'onTemplateEdit',
  'onTemplateDelete',
  'onClearConfirm',
  'onAddPanel',
  'onPanelChange',
]

/**
 * Wrap business callbacks with safeCall (R3 W2 isolation).
 *
 * @param {object} options  raw user options
 * @returns {object}        cloned options with onXxx wrapped
 */
function wrapBusinessCallbacks(options) {
  if (!options || typeof options !== 'object') return options
  const wrapped = Object.assign({}, options)
  ON_XXX_KEYS.forEach((key) => {
    const fn = wrapped[key]
    if (typeof fn === 'function') {
      wrapped[key] = function (/* ...args */) {
        return safeCall(fn, Array.prototype.slice.call(arguments), 'buildToolbar:' + key)
      }
    }
  })
  return wrapped
}

/**
 * Resolve the V1 hiprint global (set by `src/index.js`).
 *
 * @returns {object|undefined}
 */
function resolveV1Hiprint() {
  if (typeof window !== 'undefined' && window.hiprint && typeof window.hiprint.buildToolbar === 'function') {
    return window.hiprint
  }
  if (typeof globalThis !== 'undefined' && globalThis.hiprint && typeof globalThis.hiprint.buildToolbar === 'function') {
    return globalThis.hiprint
  }
  return undefined
}

/**
 * Generate a V2 toolbar uid (PM-005). Used in tests + diagnostic only;
 * the actual namespace is generated by V1 internally.
 *
 * @returns {string}
 */
export function _generateToolbarUid() {
  return (
    Date.now().toString(36) +
    '_' +
    Math.floor(Math.random() * 1679616).toString(36)
  )
}

/**
 * Build a toolbar bound to a PrintTemplate.
 *
 * @param {HTMLElement|string} container  Mount target
 * @param {object} template  V1 or V2 PrintTemplate instance
 * @param {object} [options]  See V1 buildToolbar opts (60+ fields)
 * @returns {object|undefined}  toolbar control object, or undefined if V1 bundle not loaded
 *
 * @example
 *   const ctrl = buildToolbar('#toolbar', tpl, {
 *     onPreview: (template) => console.log('preview'),
 *     showPanelManager: true,
 *   })
 *   ctrl.destroy() // 解绑所有 namespace 化 $(document) 事件
 */
export function buildToolbar(container, template, options) {
  // Container check (fail-fast helpful for tests)
  if (container == null) {
    console.warn('[hiprint-v2] buildToolbar: container is required')
    return undefined
  }
  if (template == null) {
    console.warn('[hiprint-v2] buildToolbar: template is required')
    return undefined
  }

  const v1 = resolveV1Hiprint()
  if (!v1) {
    console.warn(
      '[hiprint-v2] buildToolbar: V1 bundle not loaded (window.hiprint missing).' +
        ' P11 adapter requires V1 bundle.js side-effect to register $.fn.* and hiprint.* globals.'
    )
    return undefined
  }

  // R3 W2: wrap 24 处 onXxx business callbacks with safeCall isolation
  const wrappedOpts = wrapBusinessCallbacks(options || {})

  // Delegate to V1 (V1 internally generates _toolbarUid = Date.now() + Math.random())
  let ctrl
  try {
    ctrl = v1.buildToolbar(container, template, wrappedOpts)
  } catch (err) {
    console.error('[hiprint-v2] buildToolbar: V1 buildToolbar threw:', err)
    return undefined
  }

  // R3 W1: validate returned ctrl shape
  if (!ctrl || typeof ctrl.destroy !== 'function') {
    console.warn(
      '[hiprint-v2] buildToolbar: V1 returned ctrl missing destroy() — namespace cleanup will fail'
    )
  }

  return ctrl
}

/**
 * @internal exported for tests
 */
export const __testing__ = {
  wrapBusinessCallbacks,
  ON_XXX_KEYS,
  resolveV1Hiprint,
}
