<script setup lang="ts">
/**
 * BarcodeElement.vue — V3 barcode etype (P17.1).
 *
 * Generates a 1D barcode (default CODE128) via bwip-js, matching the V3 print
 * pipeline (`render.ts` renderBarcodeElement). We use `bwipjs.toSVG()` →
 * DOMParser → mount, same as render.ts, so designer preview and printed
 * output are visually identical.
 *
 * V1/V2 used canvas drawing; V3 uses SVG for crisper print output.
 *
 * Re-renders whenever:
 *  - The bound text (field value / testData / title fallback) changes.
 *  - barcodeType / dimensions / colors / hideTitle change.
 *
 * Safety:
 *  - SVG is generated by bwip-js from a single text input (no markup injection).
 *  - The optional title fallback is escaped via Vue interpolation.
 */
import bwipjs from 'bwip-js/browser'
import { computed, ref, watch } from 'vue'
import { useCanvasStore } from '@hiprint-v3/stores'
import { mapBarcodeMode, safeNumber, pt } from '@hiprint-v3/internal'
import ElementWrapper from './ElementWrapper.vue'
import { getElementValue, isTrue, type Opts } from './_helpers'

const props = withDefaults(
  defineProps<{
    elementId: string
    panelId: string
    data?: Record<string, unknown>
    interactive?: boolean
  }>(),
  { interactive: true }
)

const canvas = useCanvasStore()
const containerEl = ref<HTMLDivElement | null>(null)

const element = computed(() => {
  for (const panel of canvas.panels) {
    const el = panel.printElements.find((e) => e.id === props.elementId)
    if (el) return el
  }
  return null
})

const barcodeText = computed<string>(() => {
  const el = element.value
  if (!el) return ''
  const opts = el.options as Opts
  const value = getElementValue(el, props.data)
  return (
    (typeof value === 'string' && value) ||
    (typeof opts.testData === 'string' && opts.testData) ||
    (typeof opts.title === 'string' && opts.title) ||
    ''
  )
})

/** Render the SVG into the container. Wipes previous output first. */
function render(): void {
  const el = element.value
  const host = containerEl.value
  if (!el || !host) return
  // Clear previous SVG.
  while (host.firstChild) host.removeChild(host.firstChild)

  const opts = el.options as Opts
  const text = barcodeText.value
  if (!text) return

  try {
    const widthPt = safeNumber(opts.width, { min: 0, fallback: 100 })
    const heightPt = safeNumber(opts.height, { min: 0, fallback: 30 })
    const lineH = safeNumber(opts.lineHeight, {
      fallback: safeNumber(opts.fontSize, { fallback: 10.5 }) * 1.5,
    })
    const hideTitle = isTrue(opts.hideTitle)
    const titleH = !hideTitle ? lineH : 0
    const heightMm = Math.max(0, pt.toMm(heightPt - titleH))
    const widthMm = Math.max(0, pt.toMm(widthPt))
    const barAutoWidth = isTrue(opts.barAutoWidth)

    // Sprint 22g GC — V1 `barTextMode` quirk (mirror of render.ts barcode).
    // 'text' → external <div class="hibarcode_displayValue"> below the SVG.
    // 'svg' / default → text rendered inside the SVG by bwip-js itself.
    const barTextMode =
      typeof opts.barTextMode === 'string' ? opts.barTextMode : ''
    const externalText = barTextMode === 'text'

    // TKT-023: prefer Path B `barcodeType`; fall back to V1 Path A
    // `barcodeMode` (CODE128 / EAN13 / ... 18 enum) via compat mapping.
    const bcid =
      typeof opts.barcodeType === 'string' && opts.barcodeType
        ? opts.barcodeType
        : mapBarcodeMode(
            typeof opts.barcodeMode === 'string' ? opts.barcodeMode : undefined
          )
    const svgStr = bwipjs.toSVG({
      bcid,
      text,
      scale: safeNumber(opts.barWidth, { fallback: 1, min: 1 }),
      width: !barAutoWidth ? Math.floor(widthMm) : ('' as unknown as number),
      height: Math.floor(heightMm),
      includetext: !hideTitle && !externalText,
      textsize: Math.floor(safeNumber(opts.fontSize, { fallback: 10 })),
      barcolor: typeof opts.barColor === 'string' ? opts.barColor : '#000',
    } as Parameters<typeof bwipjs.toSVG>[0])

    const svgEl = parseSvg(svgStr)
    if (svgEl) {
      svgEl.setAttribute('preserveAspectRatio', 'none slice')
      host.appendChild(svgEl)
    } else {
      const fallback = document.createElement('div')
      fallback.textContent = 'Barcode render failed'
      host.appendChild(fallback)
    }
    // Sprint 22g GC — separate text line below SVG when barTextMode === 'text'.
    if (externalText && !hideTitle) {
      const dv = document.createElement('div')
      dv.classList.add('hibarcode_displayValue')
      dv.style.whiteSpace = 'nowrap'
      dv.textContent = text // [Invariant #1] textContent escapes
      host.appendChild(dv)
    }
  } catch (err) {
    console.warn('[hiprint-v3:BarcodeElement] render failed:', err)
    const fallback = document.createElement('div')
    fallback.textContent = 'Barcode render failed'
    host.appendChild(fallback)
  }
}

function parseSvg(svgStr: string): SVGElement | null {
  if (!svgStr || typeof svgStr !== 'string') return null
  try {
    const parser = new DOMParser()
    const doc = parser.parseFromString(svgStr, 'image/svg+xml')
    const errEl = doc.getElementsByTagName('parsererror')[0]
    if (errEl) return null
    const root = doc.documentElement
    if (!root || root.tagName.toLowerCase() !== 'svg') return null
    return document.importNode(root, true) as unknown as SVGElement
  } catch (err) {
    console.warn('[hiprint-v3:BarcodeElement] parseSvg failed:', err)
    return null
  }
}

// Re-render whenever the resolved text or options change. We watch the
// element itself (deep) so any options patch in the canvas store triggers
// a re-render.
watch(
  [element, () => props.data, containerEl],
  () => render(),
  { deep: true, flush: 'post' }
)
</script>

<template>
  <ElementWrapper
    :element-id="elementId"
    :panel-id="panelId"
    :interactive="interactive"
  >
    <div
      ref="containerEl"
      class="hiprint-printElement-barcode-content"
      style="height: 100%; width: 100%"
    />
  </ElementWrapper>
</template>
